# Generated by Django 4.2 on 2025-08-15 15:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('name', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phone', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('form', models.FileField(blank=True, null=True, upload_to='cv_form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updeated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
