# Generated by Django 4.2 on 2025-08-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='position',
            new_name='PositionModel',
        ),
    ]
