# Generated by Django 4.2 on 2025-08-18 18:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_serviceworkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceworkmodel',
            name='counter',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceworkmodel',
            name='counter_para',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
