# Generated by Django 4.2 on 2025-08-18 18:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_serviceworkmodel_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('counter_para', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updeated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
