# Generated by Django 4.2 on 2025-08-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_countermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countermodel',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='countermodel',
            name='counter_para',
        ),
    ]
