# Generated by Django 4.2 on 2025-08-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_countermodel_counter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterModel',
        ),
    ]
