# Generated by Django 4.2 on 2025-08-19 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_educationexperience_resumeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeeducation',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
